"""
Outcome Consumer

读取 data/events.jsonl 中的 EXIT 事件，按 trade_id 去重后写入 OutcomeDatabase

简单用法：一次性消费全部文件（去重），可周期性运行或由 cron 调度。
"""

import json
import os
import sys
import threading
import traceback
from pathlib import Path
from analytics.outcome_db import OutcomeDatabase
from analytics.feature_hash import generate_feature_hash
from analytics.outcome_learning import OutcomeLearner
from analytics.training_validator import validate_trade_sample
import logging
logger = logging.getLogger(__name__)
import time

# 线程文件锁（防止多线程同时操作 JSON 文件导致损坏）
_file_lock = threading.Lock()

# 学习版本号（便于后续比较不同版本学习结果）
LEARNING_VERSION = "58.9"

PROCESSED_FILE = Path("data/processed_trade_ids.json")
EVENT_FILE = Path("data/events.jsonl")
OPEN_CACHE_FILE = Path("data/open_cache.json")
# open cache max age (seconds)
MAX_CACHE_AGE = 7 * 24 * 3600


def load_processed():
    try:
        if PROCESSED_FILE.exists():
            return set(json.loads(PROCESSED_FILE.read_text(encoding='utf-8')))
    except Exception:
        pass
    return set()


def save_processed(s: set):
    try:
        PROCESSED_FILE.parent.mkdir(parents=True, exist_ok=True)
        PROCESSED_FILE.write_text(json.dumps(list(s), ensure_ascii=False), encoding='utf-8')
    except Exception:
        pass






def process_events_once():
    # 加文件锁，防止多线程同时操作 events.jsonl / outcome_stats.json
    global _file_lock
    with _file_lock:
        return _process_events_once_locked()


def _process_events_once_locked():
    try:
        db = OutcomeDatabase()
    except Exception as e:
        logger.error(f"[OutcomeConsumer] 创建 OutcomeDatabase 失败: {e}", exc_info=True)
        return 0
    
        # ★★★ 关键修复：必须加载已处理的 trade_id 集合（之前错误地设为了 None）★★★
    processed = load_processed()
    if not EVENT_FILE.exists():
        return 0

    new_processed = set()
    processed_count = 0

    # 先加载持久化的 OPEN 缓存（用于重启恢复）
    open_cache = {}
    try:
        if OPEN_CACHE_FILE.exists():
            open_cache = json.loads(OPEN_CACHE_FILE.read_text(encoding='utf-8')) or {}
    except Exception:
        open_cache = {}

    # 清理过期的 open_cache 条目（防止长期未平仓造成学习污染）
    try:
        from datetime import datetime
        now_ts = datetime.utcnow().timestamp()
        stale = []
        for tid, rec in list(open_cache.items()):
            ts = None
            try:
                tstr = rec.get('timestamp')
                if tstr:
                    try:
                        from datetime import datetime as _dt
                        ts = _dt.fromisoformat(tstr).timestamp()
                    except Exception:
                        try:
                            ts = float(tstr)
                        except Exception:
                            ts = None
            except Exception:
                ts = None
            if ts is None or (now_ts - ts) > MAX_CACHE_AGE:
                stale.append(tid)
        if stale:
            # 为每个 stale open 生成 FORCE_CLOSE_UNKNOWN 事件并写入 events 文件，避免后续学习中丢失 OPEN
            try:
                EVENT_FILE.parent.mkdir(parents=True, exist_ok=True)
                with EVENT_FILE.open('a', encoding='utf-8') as ef:
                    import uuid
                    from datetime import datetime as _dt
                    for tid in stale:
                        rec = open_cache.get(tid, {})
                        ev = {
                            'event': 'FORCE_CLOSE_UNKNOWN',
                            'schema_version': '58.9',
                            'event_id': str(uuid.uuid4()),
                            'timestamp': _dt.utcnow().isoformat(),
                            'trade_id': tid,
                            'symbol': rec.get('symbol'),
                            'features': rec.get('features'),
                            'regime': rec.get('regime'),
                            'score': rec.get('score'),
                            'note': 'auto-generated by open_cache cleanup (expired)'
                        }
                        ef.write(json.dumps(ev, ensure_ascii=False) + '\n')
            except Exception:
                pass
            # 从缓存中移除
            for tid in stale:
                try:
                    del open_cache[tid]
                except Exception:
                    pass
            try:
                OPEN_CACHE_FILE.write_text(json.dumps(open_cache, ensure_ascii=False), encoding='utf-8')
            except Exception:
                pass
    except Exception:
        pass

    # 读入全部事件（文件通常不大），并从文件中补充 OPEN 到缓存
    events = []
    with EVENT_FILE.open('r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
            except Exception:
                continue
            events.append(ev)
            if ev.get('event') == 'OPEN':
                tid = ev.get('trade_id') or ev.get('event_id')
                if tid:
                    # 仅保留必要字段以减小缓存体积
                    open_cache[tid] = {
                        "symbol": ev.get('symbol'),
                        "features": ev.get('features'),
                        "regime": ev.get('regime'),
                        "score": ev.get('score'),
                        "ev": ev.get('ev'),
                        "confidence": ev.get('confidence'),
                        "timestamp": ev.get('timestamp'),
                    }

    # 持久化 OPEN 缓存
    try:
        OPEN_CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
        OPEN_CACHE_FILE.write_text(json.dumps(open_cache, ensure_ascii=False), encoding='utf-8')
    except Exception:
        pass

    # 处理 EXIT 与 FORCE_CLOSE_UNKNOWN 事件，使用 OPEN 缓存补全 fields
    for ev in events:
        # P0: 完全隔离异常交易 —— 必须在 feature_hash / OutcomeDB / Learning 之前拦截
        # FORCE_CLOSE_UNKNOWN 可能以两种形式出现：
        #   1) event = "FORCE_CLOSE_UNKNOWN"（open_cache 过期清理自动生成）
        #   2) event = "EXIT" 且 reason = "FORCE_CLOSE_UNKNOWN"（外部平仓带异常原因）
        reason = ev.get("reason")
        if ev.get('event') == 'FORCE_CLOSE_UNKNOWN' or reason == 'FORCE_CLOSE_UNKNOWN':
            trade_id = ev.get('trade_id')
            dedupe_key = trade_id or ev.get('event_id')
            # ★ 去重检查：已处理过的异常关闭不再重复处理
            if dedupe_key and dedupe_key in processed:
                continue
            logger.warning(f"[Outcome] Skip abnormal close {trade_id}: reason={reason or 'FORCE_CLOSE_UNKNOWN'}")
            # 彻底移除 open_cache 条目，不写入 OutcomeDB/学习
            try:
                if trade_id and trade_id in open_cache:
                    del open_cache[trade_id]
                    OPEN_CACHE_FILE.write_text(json.dumps(open_cache, ensure_ascii=False), encoding='utf-8')
            except Exception:
                pass
            if dedupe_key:
                new_processed.add(dedupe_key)
                processed_count += 1
            continue

        # 仅处理 EXIT 事件
        if ev.get('event') != 'EXIT':
            continue
        trade_id = ev.get('trade_id')
        dedupe_key = trade_id or ev.get('event_id')
        if dedupe_key and dedupe_key in processed:
            continue

        # 合并 OPEN + EXIT，EXIT 优先覆盖 OPEN 字段
        merged = {}
        if trade_id and trade_id in open_cache:
            merged.update(open_cache[trade_id])
        merged.update(ev)
        # 合并后二次防御：即使 EXIT 里 reason 合法但 OPEN 缓存被毒化，也拦截
        if merged.get('event') == 'FORCE_CLOSE_UNKNOWN' or merged.get('reason') == 'FORCE_CLOSE_UNKNOWN':
            logger.warning(f"[Outcome] skip learning unknown close (post-merge): {dedupe_key}")
            try:
                if trade_id and trade_id in open_cache:
                    del open_cache[trade_id]
                    OPEN_CACHE_FILE.write_text(json.dumps(open_cache, ensure_ascii=False), encoding='utf-8')
            except Exception:
                pass
            if dedupe_key:
                new_processed.add(dedupe_key)
                processed_count += 1
            continue

        # 训练样本质量校验
        if not validate_trade_sample(merged):
            logger.warning(f"[Outcome] sample rejected by TrainingValidator: {dedupe_key}")
        else:
            # 计算 feature hash 并写入 OutcomeDatabase
            features = merged.get('features') or {}
            feature_hash = generate_feature_hash(features) if isinstance(features, dict) else generate_feature_hash({})
            profit_r = float(merged.get('profit_r') or merged.get('pnl_r') or 0.0)
            try:
                db.update(feature_hash, profit_r, mode=merged.get('mode','NORMAL'))
            except Exception as e:
                print(f"OutcomeDB update failed: {e}")

            # 同步触发学习模块更新（携带学习版本号）
            try:
                learner = OutcomeLearner()
                learner.update_from_trade(merged.get('features') or {}, profit_r, mode=merged.get('mode','NORMAL'), learning_version=LEARNING_VERSION)
            except Exception as e:
                print(f"OutcomeLearner update failed: {e}")

        if dedupe_key:
            new_processed.add(dedupe_key)
            processed_count += 1
            # 已消费的 trade_id 从 open_cache 移除并持久化
            try:
                if trade_id and trade_id in open_cache:
                    del open_cache[trade_id]
                    OPEN_CACHE_FILE.write_text(json.dumps(open_cache, ensure_ascii=False), encoding='utf-8')
            except Exception:
                pass
    # 持久化已处理 id
    if new_processed:
        processed.update(new_processed)
        save_processed(processed)
    return processed_count













def start_worker(poll_interval: float = 30.0):
    """
    持续轮询 events.jsonl 并消费 EXIT 事件，适合在后台线程中运行

    关键修复（防止线程静默死亡）：
    1. 全局 try...except 捕获所有异常并打印堆栈
    2. 每轮输出心跳日志证明线程存活
    3. 连续错误时自动增加等待时间避免疯狂重试
    """
    thread_name = threading.current_thread().name
    logger.info(f"[OutcomeConsumer] 影子闭环轮询线程已启动 (thread={thread_name}, poll_interval={poll_interval}s)")
    print(f"[OutcomeConsumer] worker started (thread={thread_name}, poll_interval={poll_interval}s)", flush=True)
    
    consecutive_errors = 0
    max_consecutive_errors = 10  # 连续 10 次错误后降低轮询频率
    
    while True:
        try:
            # 核心业务逻辑
            n = process_events_once()
            
            if n:
                logger.info(f"[OutcomeConsumer] 消费了 {n} 个 EXIT 事件")
                print(f"[OutcomeConsumer] Consumed {n} EXIT events", flush=True)
            else:
                # 心跳日志（每轮输出，证明线程活着）
                logger.debug(f"[OutcomeConsumer] 本轮扫描完成，无新事件 (thread={thread_name})")
            
            # 重置错误计数
            consecutive_errors = 0
            
        except KeyboardInterrupt:
            logger.warning("[OutcomeConsumer] worker 被 KeyboardInterrupt 中断")
            print("OutcomeConsumer worker stopped")
            break
            
        except Exception as e:
            # ★★★ 关键修复：捕获所有异常，绝不静默死亡 ★★★
            consecutive_errors += 1
            logger.error(
                f"[OutcomeConsumer] 轮询过程发生严重异常 (第 {consecutive_errors} 次): {e}\\n"
                f"堆栈:\\n{traceback.format_exc()}"
            )
            print(f"[OutcomeConsumer] ERROR: {e}", flush=True)
            
            # 如果连续出错，增加等待时间避免疯狂重试
            if consecutive_errors >= max_consecutive_errors:
                logger.critical(f"[OutcomeConsumer] 连续 {consecutive_errors} 次错误，延长等待时间至 60s")
                time.sleep(60)
                consecutive_errors = 0  # 重置，继续尝试
                continue
        
        finally:
            # 保持固定轮询间隔
            time.sleep(poll_interval)


def start_worker_with_monitor(poll_interval: float = 30.0):
    """
    启动 OutcomeConsumer worker 并附带监控保护
    
    监控线程每轮询间隔检查主线程是否存活，如果死亡则自动重启
    返回: 启动的 worker 线程
    """
    global _worker_thread_ref
    
    # 主 worker 线程
    worker_thread = threading.Thread(
        target=start_worker,
        args=(poll_interval,),
        name="OutcomeConsumer",
        daemon=True
    )
    worker_thread.start()
    _worker_thread_ref = worker_thread
    
    logger.info(f"[OutcomeConsumer-Monitor] 主 worker 线程已启动: {worker_thread.name} (ID: {worker_thread.ident})")
    
    # 监控线程：检测 worker 死亡并自动重启
    def _monitor():
        monitor_name = threading.current_thread().name
        logger.info(f"[OutcomeConsumer-Monitor] 监控线程启动: {monitor_name}")
        
        while True:
            time.sleep(poll_interval)  # 每轮询间隔检查一次
            
            # 获取当前 worker 线程引用
            global _worker_thread_ref
            current = _worker_thread_ref
            
            # 检查主线程是否还活着
            if current is not None and current.is_alive():
                logger.debug(f"[OutcomeConsumer-Monitor] 主线程存活 (health check ok)")
            else:
                logger.critical(
                    f"[OutcomeConsumer-Monitor] ★★★ 检测到 OutcomeConsumer 线程已死亡！立即重启... ★★★"
                )
                print(f"[OutcomeConsumer-Monitor] DETECTED THREAD DEATH - restarting...", flush=True)
                
                # 尝试重启新线程
                try:
                    new_thread = threading.Thread(
                        target=start_worker,
                        args=(poll_interval,),
                        name="OutcomeConsumer-Restarted",
                        daemon=True
                    )
                    new_thread.start()
                    _worker_thread_ref = new_thread
                    logger.info(f"[OutcomeConsumer-Monitor] 新线程已启动: {new_thread.name} (ID: {new_thread.ident})")
                except Exception as e:
                    logger.critical(f"[OutcomeConsumer-Monitor] 重启线程失败: {e}", exc_info=True)
                
                # 等待 5 秒后继续监控
                time.sleep(5)
    
    monitor_thread = threading.Thread(
        target=_monitor,
        name="OutcomeConsumerMonitor",
        daemon=True
    )
    monitor_thread.start()
    
    return worker_thread


# 全局引用（用于监控线程检查）
_worker_thread_ref = None


if __name__ == '__main__':
    n = process_events_once()
    print(f"Processed {n} EXIT events.")
