"""
Outcome Consumer

读取 data/events.jsonl 中的 EXIT 事件，按 trade_id 去重后写入 OutcomeDatabase

简单用法：一次性消费全部文件（去重），可周期性运行或由 cron 调度。
"""

import json
from pathlib import Path
from analytics.outcome_db import OutcomeDatabase
from analytics.feature_hash import generate_feature_hash
from analytics.outcome_learning import OutcomeLearner
from analytics.training_validator import validate_trade_sample
import logging
logger = logging.getLogger(__name__)
import time

# 学习版本号（便于后续比较不同版本学习结果）
LEARNING_VERSION = "58.9"

PROCESSED_FILE = Path("data/processed_trade_ids.json")
EVENT_FILE = Path("data/events.jsonl")
OPEN_CACHE_FILE = Path("data/open_cache.json")
# open cache max age (seconds)
MAX_CACHE_AGE = 7 * 24 * 3600


def load_processed():
    try:
        if PROCESSED_FILE.exists():
            return set(json.loads(PROCESSED_FILE.read_text(encoding='utf-8')))
    except Exception:
        pass
    return set()


def save_processed(s: set):
    try:
        PROCESSED_FILE.parent.mkdir(parents=True, exist_ok=True)
        PROCESSED_FILE.write_text(json.dumps(list(s), ensure_ascii=False), encoding='utf-8')
    except Exception:
        pass


def process_events_once():
    db = OutcomeDatabase()
    processed = load_processed()
    if not EVENT_FILE.exists():
        return 0

    new_processed = set()
    processed_count = 0

    # 先加载持久化的 OPEN 缓存（用于重启恢复）
    open_cache = {}
    try:
        if OPEN_CACHE_FILE.exists():
            open_cache = json.loads(OPEN_CACHE_FILE.read_text(encoding='utf-8')) or {}
    except Exception:
        open_cache = {}

    # 清理过期的 open_cache 条目（防止长期未平仓造成学习污染）
    try:
        from datetime import datetime
        now_ts = datetime.utcnow().timestamp()
        stale = []
        for tid, rec in list(open_cache.items()):
            ts = None
            try:
                tstr = rec.get('timestamp')
                if tstr:
                    try:
                        from datetime import datetime as _dt
                        ts = _dt.fromisoformat(tstr).timestamp()
                    except Exception:
                        try:
                            ts = float(tstr)
                        except Exception:
                            ts = None
            except Exception:
                ts = None
            if ts is None or (now_ts - ts) > MAX_CACHE_AGE:
                stale.append(tid)
        if stale:
            # 为每个 stale open 生成 FORCE_CLOSE_UNKNOWN 事件并写入 events 文件，避免后续学习中丢失 OPEN
            try:
                EVENT_FILE.parent.mkdir(parents=True, exist_ok=True)
                with EVENT_FILE.open('a', encoding='utf-8') as ef:
                    import uuid
                    from datetime import datetime as _dt
                    for tid in stale:
                        rec = open_cache.get(tid, {})
                        ev = {
                            'event': 'FORCE_CLOSE_UNKNOWN',
                            'schema_version': '58.9',
                            'event_id': str(uuid.uuid4()),
                            'timestamp': _dt.utcnow().isoformat(),
                            'trade_id': tid,
                            'symbol': rec.get('symbol'),
                            'features': rec.get('features'),
                            'regime': rec.get('regime'),
                            'score': rec.get('score'),
                            'note': 'auto-generated by open_cache cleanup (expired)'
                        }
                        ef.write(json.dumps(ev, ensure_ascii=False) + '\n')
            except Exception:
                pass
            # 从缓存中移除
            for tid in stale:
                try:
                    del open_cache[tid]
                except Exception:
                    pass
            try:
                OPEN_CACHE_FILE.write_text(json.dumps(open_cache, ensure_ascii=False), encoding='utf-8')
            except Exception:
                pass
    except Exception:
        pass

    # 读入全部事件（文件通常不大），并从文件中补充 OPEN 到缓存
    events = []
    with EVENT_FILE.open('r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
            except Exception:
                continue
            events.append(ev)
            if ev.get('event') == 'OPEN':
                tid = ev.get('trade_id') or ev.get('event_id')
                if tid:
                    # 仅保留必要字段以减小缓存体积
                    open_cache[tid] = {
                        "symbol": ev.get('symbol'),
                        "features": ev.get('features'),
                        "regime": ev.get('regime'),
                        "score": ev.get('score'),
                        "ev": ev.get('ev'),
                        "confidence": ev.get('confidence'),
                        "timestamp": ev.get('timestamp'),
                    }

    # 持久化 OPEN 缓存
    try:
        OPEN_CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
        OPEN_CACHE_FILE.write_text(json.dumps(open_cache, ensure_ascii=False), encoding='utf-8')
    except Exception:
        pass

    # 处理 EXIT 与 FORCE_CLOSE_UNKNOWN 事件，使用 OPEN 缓存补全 fields
    for ev in events:
        # P0: 完全隔离异常交易 —— 必须在 feature_hash / OutcomeDB / Learning 之前拦截
        # FORCE_CLOSE_UNKNOWN 可能以两种形式出现：
        #   1) event = "FORCE_CLOSE_UNKNOWN"（open_cache 过期清理自动生成）
        #   2) event = "EXIT" 且 reason = "FORCE_CLOSE_UNKNOWN"（外部平仓带异常原因）
        reason = ev.get("reason")
        if ev.get('event') == 'FORCE_CLOSE_UNKNOWN' or reason == 'FORCE_CLOSE_UNKNOWN':
            trade_id = ev.get('trade_id')
            dedupe_key = trade_id or ev.get('event_id')
            logger.warning(f"[Outcome] Skip abnormal close {trade_id}: reason={reason or 'FORCE_CLOSE_UNKNOWN'}")
            # 彻底移除 open_cache 条目，不写入 OutcomeDB/学习
            try:
                if trade_id and trade_id in open_cache:
                    del open_cache[trade_id]
                    OPEN_CACHE_FILE.write_text(json.dumps(open_cache, ensure_ascii=False), encoding='utf-8')
            except Exception:
                pass
            if dedupe_key:
                new_processed.add(dedupe_key)
                processed_count += 1
            continue

        # 仅处理 EXIT 事件
        if ev.get('event') != 'EXIT':
            continue
        trade_id = ev.get('trade_id')
        dedupe_key = trade_id or ev.get('event_id')
        if dedupe_key and dedupe_key in processed:
            continue

        # 合并 OPEN + EXIT，EXIT 优先覆盖 OPEN 字段
        merged = {}
        if trade_id and trade_id in open_cache:
            merged.update(open_cache[trade_id])
        merged.update(ev)
        # 合并后二次防御：即使 EXIT 里 reason 合法但 OPEN 缓存被毒化，也拦截
        if merged.get('event') == 'FORCE_CLOSE_UNKNOWN' or merged.get('reason') == 'FORCE_CLOSE_UNKNOWN':
            logger.warning(f"[Outcome] skip learning unknown close (post-merge): {dedupe_key}")
            try:
                if trade_id and trade_id in open_cache:
                    del open_cache[trade_id]
                    OPEN_CACHE_FILE.write_text(json.dumps(open_cache, ensure_ascii=False), encoding='utf-8')
            except Exception:
                pass
            if dedupe_key:
                new_processed.add(dedupe_key)
                processed_count += 1
            continue

        # 训练样本质量校验
        if not validate_trade_sample(merged):
            logger.warning(f"[Outcome] sample rejected by TrainingValidator: {dedupe_key}")
        else:
            # 计算 feature hash 并写入 OutcomeDatabase
            features = merged.get('features') or {}
            feature_hash = generate_feature_hash(features) if isinstance(features, dict) else generate_feature_hash({})
            profit_r = float(merged.get('profit_r') or merged.get('pnl_r') or 0.0)
            try:
                db.update(feature_hash, profit_r, mode=merged.get('mode','NORMAL'))
            except Exception as e:
                print(f"OutcomeDB update failed: {e}")

            # 同步触发学习模块更新（携带学习版本号）
            try:
                learner = OutcomeLearner()
                learner.update_from_trade(merged.get('features') or {}, profit_r, mode=merged.get('mode','NORMAL'), learning_version=LEARNING_VERSION)
            except Exception as e:
                print(f"OutcomeLearner update failed: {e}")

        if dedupe_key:
            new_processed.add(dedupe_key)
            processed_count += 1
            # 已消费的 trade_id 从 open_cache 移除并持久化
            try:
                if trade_id and trade_id in open_cache:
                    del open_cache[trade_id]
                    OPEN_CACHE_FILE.write_text(json.dumps(open_cache, ensure_ascii=False), encoding='utf-8')
            except Exception:
                pass
    # 持久化已处理 id
    if new_processed:
        processed.update(new_processed)
        save_processed(processed)
    return processed_count


def start_worker(poll_interval: float = 30.0):
    """持续轮询 events.jsonl 并消费 EXIT 事件，适合在后台线程中运行"""
    print(f"OutcomeConsumer worker started, polling every {poll_interval}s")
    try:
        while True:
            n = process_events_once()
            if n:
                print(f"Consumed {n} EXIT events")
            time.sleep(poll_interval)
    except KeyboardInterrupt:
        print("OutcomeConsumer worker stopped")


if __name__ == '__main__':
    n = process_events_once()
    print(f"Processed {n} EXIT events.")
